      PROGRAM CIRC
!   COMPUTE CIRCUMFERENCE OF A CIRCLE
      REAL PI, RADIUS, CIRCUM
      PRINT *, "ENTER RADIUS"
      READ *, RADIUS
      PI=3.14159
      CIRCUM=2*PI*RADIUS
      PRINT *, "RADIUS = ",RADIUS, "CIRCUMFERENCE = ",CIRCUM
      END PROGRAM CIRC
